language: bash
services: docker

env:
  - VERSION=9.5

before_script:
  - env | sort
  - image="nebirhos/postgres-replication:$VERSION"

script:
  - docker build -t "$image" .
  - ./tests/run.sh "$image"

after_script:
  - docker images
